// <auto-generated />
using EntityFrameworkCoreApiSamples.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCoreApiSamples.Migrations
{
    [DbContext(typeof(TodosContext))]
    [Migration("20231016120651_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.23");

            modelBuilder.Entity("EntityFrameworkCoreApiSamples.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("todo_name");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Project management"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCoreApiSamples.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("todo_item_description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("todo_item_is_completed");

                    b.Property<int>("TodoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("TodoItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create a Database Context",
                            IsCompleted = false,
                            TodoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create Todo entity",
                            IsCompleted = false,
                            TodoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Create TodoItem entity",
                            IsCompleted = false,
                            TodoId = 1
                        });
                });

            modelBuilder.Entity("EntityFrameworkCoreApiSamples.Models.TodoItem", b =>
                {
                    b.HasOne("EntityFrameworkCoreApiSamples.Models.Todo", "Todo")
                        .WithMany("TodoItems")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("EntityFrameworkCoreApiSamples.Models.Todo", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
